# Configuración de EscapesJ
afip.token=bQBOt9XSByxKnnOFqyklvXmQxneRxrGltGoB0FiE6191msWEIg3YB5fexH4pUUWe
afip.base_url=https://apis.afip.gov.ar
# config.properties
db.url=jdbc:mysql://localhost:3306/escapesj
db.user=tu_usuario
db.password=tu_contraseña